#!/usr/bin/env python3
import os as _os_timing, time as _time_module
if _os_timing.environ.get('TW_TIMING'):
    import atexit as _atexit
    _t0 = _time_module.perf_counter()

    def _report_timing(_f=__file__):
        elapsed = (_time_module.perf_counter() - _t0) * 1000
        import os.path as _osp
        print(f"[timing] {_osp.basename(_f)}: {elapsed:.1f}ms", file=__import__('sys').stderr)

    _atexit.register(_report_timing)

"""
on-launch_smart-nag.py - Smart configurable nag for Taskwarrior
Version: 0.1.0

Replaces TW's native nag message with the first matching condition from
smart-nag.rc. Writes rc.nag= to ~/.taskrc via `task config` before each
TW invocation — native nag trigger still controls when it fires.

Install:
  cp on-launch_smart-nag.py ~/.task/hooks/on-launch_smart-nag.py
  chmod +x ~/.task/hooks/on-launch_smart-nag.py

  # Optional: include smart-nag.rc in ~/.taskrc for sanity-check integration:
  #   include ~/.task/config/smart-nag.rc
"""

# ============================================================================
# DEBUG VERSION - Auto-generated by make-awesome.py
# ============================================================================

import os
import sys
from pathlib import Path
from datetime import datetime
import subprocess

# Debug configuration (default 0, triggered by tw --debug=2)
DEBUG_MODE = 0

tw_debug_level = os.environ.get('TW_DEBUG', '0')
try:
    tw_debug_level = int(tw_debug_level)
except ValueError:
    tw_debug_level = 0

debug_active = DEBUG_MODE == 1 or tw_debug_level >= 2

def get_log_dir():
    cwd = Path.cwd()
    if (cwd / '.git').exists():
        log_dir = cwd / 'logs' / 'debug'
    else:
        log_dir = Path.home() / '.task' / 'logs' / 'debug'
    log_dir.mkdir(parents=True, exist_ok=True)
    return log_dir

if debug_active:
    DEBUG_LOG_DIR = get_log_dir()
    DEBUG_SESSION_ID = datetime.now().strftime("%Y%m%d_%H%M%S")
    try:
        script_name = Path(__file__).stem
    except:
        script_name = Path(sys.argv[0]).stem if sys.argv else "script"
    DEBUG_LOG_FILE = DEBUG_LOG_DIR / f"{script_name}_debug_{DEBUG_SESSION_ID}.log"
    
    def debug_log(message, level=1):
        if debug_active and tw_debug_level >= level:
            timestamp = datetime.now().strftime("%H:%M:%S.%f")[:-3]
            log_line = f"{timestamp} [DEBUG-{level}] {message}\n"
            with open(DEBUG_LOG_FILE, "a") as f:
                f.write(log_line)
            print(f"\033[34m[DEBUG-{level}]\033[0m {message}", file=sys.stderr)
    
    with open(DEBUG_LOG_FILE, "w") as f:
        f.write("=" * 70 + "\n")
        f.write(f"Debug Session - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"Script: {script_name}\n")
        f.write(f"TW_DEBUG Level: {tw_debug_level}\n")
        f.write("=" * 70 + "\n\n")
    debug_log(f"Debug logging initialized: {DEBUG_LOG_FILE}", 1)
else:
    def debug_log(message, level=1):
        pass

# ============================================================================
# Original Code
# ============================================================================

sys.path.insert(0, os.path.expanduser('~/.task/scripts'))
sys.path.insert(0, os.path.expanduser('~/dev/awesome-taskwarrior/lib'))
from tw_condition_lib import compute_action, load_rc, sort_tasks
from tw_hook_lib import task_export

VERSION = '0.1.0'
NAG_RC  = Path.home() / '.task' / 'config' / 'smart-nag.rc'


def main():
    # on-launch protocol: read stdin and echo it back
    for line in sys.stdin:
        sys.stdout.write(line)

    _, conditions = load_rc(NAG_RC, app_prefix='nag')

    message = ''
    for cond in conditions:
        if cond.get('type', 'nag') != 'nag':
            continue
        filt = cond.get('filter', '').strip()
        if not filt:
            continue
        tasks = task_export(filt.split())
        if not tasks:
            continue
        tasks = sort_tasks(tasks, cond.get('sort', ''))
        message = compute_action(cond.get('msg', ''), tasks[0], count=len(tasks))
        if message:
            break

    subprocess.run(
        ['task', 'rc.hooks=off', 'rc.confirmation=off', 'rc.verbose=nothing',
         'config', 'nag', message],
        capture_output=True
    )
    sys.exit(0)


if __name__ == '__main__':
    main()
